export const categories = [
     "backrounds",
     "animals",
     "nature",
     "people",
     "tech",
     "sports",
     "travel",
     "objects",
     "fashion",
     "food",
     "animals_wildlife",
     "human_body",
     "buildings",
     "clothing",
     "home",
     "sports_games",
];
